export default {

    LOGIN:'LOGIN',
    ADD_DATA:'HOMEPAGE',
   DELETE_ITEM:'DELETE_ITEM',
   CHANGE_VALUE:"CHANGE_VALUE",
   DECREMENT_VALUE:"DECREMENT_VALUE",
   TOTAL_PRICE:"TOTAL_PRICE",
//    ITEM:"ITEM"
}